[package]
name = "kahl"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = { version = "1", default-features = false, features = ["std", "perf", "unicode-perl"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
